[package]
name = "rengine"
version = "0.1.0"
authors = ["justin wash <justin.wash@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luminance = "0.43"
luminance-glfw = "0.14"
luminance-windowing = "0.9"
luminance-derive = "0.6"
luminance-gl = "0.16.1"
glfw = "0.41"
image = "0.23.12"
uuid = { version = "0.8", features = ["serde", "v4"] }